# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  # 端口号
  port: 8080
  # 超时时间
  connection-timeout: 5000

spring:
  # RabbitMQ设置
  rabbitmq:
    # 访问地址
    host: 82.157.231.97
    # 端口
    port: 5672
    # 用户名
    username: admin
    # 密码
    password: admin
    # 监听设置
    listener:
      # 生产者
      direct:
        # 自动启动开关
        auto-startup: false
      # 消费者
      simple:
        # 自动启动开关
        auto-startup: false

  application:
    # 应用名称。如果启用nacos，此值必填
    name: com.thinkdifferent.convertoffice
  cloud:
    # Nacos的配置。
    # 如果启用Nacos服务作为配置中心，
    # 则此部分之后的内容均可以在Nacos配置中心中管理，
    # 不必在此配置文件中维护。
    nacos:
      config:
        # 配置服务地址
        server-addr: 82.157.231.97:8848
        # 启用状态
        enabled: true
      discovery:
        # 服务发现服务地址
        server-addr: 82.157.231.97:8848
        # 启用状态
        enabled: true


# log4j2设置
logging:
  # 配置文件名
  config: log4j2.xml
  level:
    com.thinkdifferent: trace

# 线程设置参数 #######
ThreadPool:
  # 核心线程数10：线程池创建时候初始化的线程数
  CorePoolSize: 10
  # 最大线程数20：线程池最大的线程数，只有在缓冲队列满了之后才会申请超过核心线程数的线程
  MaxPoolSize: 20
  # 缓冲队列200：用来缓冲执行任务的队列
  QueueCapacity: 200
  # 保持活动时间60秒
  KeepAliveSeconds: 60
  # 允许线程的空闲时间60秒：当超过了核心线程出之外的线程在空闲时间到达之后会被销毁
  AwaitTerminationSeconds: 60

jodconverter:
  local:
    enabled: true
    # libreOffice根目录
#    office-home: D:/LibreOffice
    office-home: C:\Program Files\LibreOffice
    # 端口（线程）
    portNumbers: [2001,2002,2003]
    # LibreOffice进程重启前的最大进程数
    maxTasksPerProcess: 100
    # 任务执行的超时时间
    taskExecutionTimeout: 86400000
    # 任务队列的超时时间
    taskQueueTimeout: 86400000
    # 一个进程的超时时间
    processTimeout: 86400000


# 本服务设置
convert:
  office:
    # 接收的输入文件存储的临时文件夹
    inPutTempPath: D:/cvtest/temp/
    # 默认本地输出文件所在文件夹
    outPutPath: D:/cvtest/

